{\rtf1\ansi\ansicpg1252\cocoartf2578
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0   File "server.py", line 2\
    from mysqlconnection import connectToMySQL\'a0\'a0\'a0\'a0# import the function that will return an instance of a connection\
                                                 ^\
SyntaxError: invalid character in identifier\
(py3Env) (base) takashi@Keis-Air first_flask_mysql % python server.py\
Traceback (most recent call last):\
  File "server.py", line 2, in <module>\
    from mysqlconnection import connectToMySQL # import the function that will return an instance of a connection\
  File "/Users/takashi/Desktop/Documents/CodingDojo/python_stack/flask/flask_fundamentals/first_flask_mysql/mysqlconnection.py", line 12\
    \'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0autocommit = True)\
                                                 ^\
Traceback (most recent call last):\
  File "server.py", line 2, in <module>\
    from mysqlconnection import connectToMySQL # import the function that will return an instance of a connection\
  File "/Users/takashi/Desktop/Documents/CodingDojo/python_stack/flask/flask_fundamentals/first_flask_mysql/mysqlconnection.py", line 13\
    \'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0# establish the connection to the database\
\
pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: NO)")\
pymysql.err.OperationalError: (1045, "Access denied for user 'root1'@'localhost' (using password: YES)")\
AttributeError: module 'pymysql' has no attribute 'connects'\
AttributeError: module 'pymysql' has no attribute 'connects'\
AttributeError: module 'pymysql' has no attribute 'connects'\
TypeError: 'bool' object is not iterable\
TypeError: query_db() missing 1 required positional argument: 'data'\
pymysql.err.OperationalError: (1049, "Unknown database 'friend'")}